### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by arthurTemporim** [trys/Heads-Up#1]
Hi @trys,

First, congratulations on this project, it's really good.

I would ask you, to please, add a license to the code. I want to use this code as the base of a research project and add some health examples to teach Brazilian nursing students medicine terms in a funny way.

I will keep my changes open in a fork.

Thank you very much.

**Comment by trys** [comment]
Thanks! I've added a license - good luck with the research project!

**Comment by arthurTemporim** [comment]
Thank you very much!
